### ISSUE TITLE
How to re-run Lettering?

### ISSUE THREAD

**Issue by BedrosBoost** [dmMaze/BallonsTranslator#268]
How do I make Lettering run again?

This is what I'm doing:
1. The OCR is not perfect, so sometimes I will make the program to run Text Detection, OCR, and Inpainting first.
2. After that, I will remove any SFX, re-arrange the text bubbles and re-check the OCR and fix any errors.
3. Finally, I will run Translation to get the final output

The problem:
The font size, alignment, etc. are not adjusted by the program anymore. This results in oversized texts, vertical texts, texts not in the bubbles, etc.

With my scenario, what should I do in order to get the program to translate and re-do the auto Lettering again?

Thank you.

**Comment by dmMaze** [comment]
did you try the dev version and the issue still exists?
if not, you could enable/disable these stages in titlebar-run menu:
1. disable translation and run
2. manual correction
3. enable translation and disable other stages and then run

**Comment by BedrosBoost** [comment]
Yes, I am using the dev version.
Yes, that is the procedure that I follow. The problem is that Translation does not re-do the Lettering (Font Size not suited for the bubble, quite a few text are written vertical also.

I think it is because Translation adds the text to the existing text boxes and does not change their settings. The textbox settings were done at another stage which I cannot determine.

**Comment by bropines** [comment]
> Yes, I am using the dev version. Yes, that is the procedure that I follow. The problem is that Translation does not re-do the Lettering (Font Size not suited for the bubble, quite a few text are written vertical also.
> 
> I think it is because Translation adds the text to the existing text boxes and does not change their settings. The textbox settings were done at another stage which I cannot determine.

By the way, yes, if the block has already been created, its settings will be updated only if the parameters are manually changed. I seemed to suggest a button that, when all blocks are selected, applies the current text settings. (Although apply text formanting seems to do the same thing)

**Comment by dmMaze** [comment]
[bdbbc01](https://github.com/dmMaze/BallonsTranslator/commit/bdbbc016b6b1cba596ee62464803f53a444e72cc) should fix the size problem, I didn't encounter the vertical issue so can't confirm it was resolved.

**Comment by dmMaze** [comment]
> By the way, yes, if the block has already been created, its settings will be updated only if the parameters are manually changed

can you upload a video to describ how to reproduce it?

**Comment by BedrosBoost** [comment]
> [bdbbc01](https://github.com/dmMaze/BallonsTranslator/commit/bdbbc016b6b1cba596ee62464803f53a444e72cc) should fix the size problem, I didn't encounter the vertical issue so can't confirm it was resolved.

Thanks. I won’t be in for 3 days so will only be able to test it out after that. If I encounter the vertical issue again, I’ll try to see if I can record it.

**Comment by BedrosBoost** [comment]
Hello, I have updated to the latest dev build and tested it out. The problem still seems to be there. Please find attached two recordings showing the process.

Video 1: Run all stages at the same time.
Video 2: Run 'Text Detecion', 'OCR', and 'Inpainting' together. Then Run 'Translation' after that.

Please look at the bubble for '天国...?!'. In Video 1, the font size is suitable. However in Video 2, the font size is way too big.

I have also attached my settings for Lettering.

https://github.com/dmMaze/BallonsTranslator/assets/102727507/86701339-81bc-44fa-9c65-611555c719ae


https://github.com/dmMaze/BallonsTranslator/assets/102727507/01ef463a-ac53-4ed6-a474-fe9a8d22bc0b

![settings](https://github.com/dmMaze/BallonsTranslator/assets/102727507/9a22380c-ebac-44e1-8c48-e19ebb7924b9)

**Comment by dmMaze** [comment]
739ec09 should fix the size, if you run only the translation more than 1 time and the text size keeps getting smaller, uncheck the adaptive font size adjustment in the config panel for the rest translation runs

**Comment by BedrosBoost** [comment]
It works now. Thank you very much!
